---
title: "Day 05 Practice Problems"
author: "Carey Kopeikin"
date: "3/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
```

*Reminders*

The standard deviation for a proportion is calculated as follows: 

$$\sqrt{\frac{p(1-p)}{n}}$$
The standard deviation of a mean is calculated as follows:

$$\sigma_{mean}=\frac{\sigma}{\sqrt{n}}$$
1. A garden center wants to determine the average height of tomato plants grown from seeds they sell. They measure the height of 100 plants and find the average height is 12.5 inches with a standard deviation of 2.5 inches. What is a 95% confidence interval for the average height of tomato plants grown from these seeds?

2. A newspaper wants to determine the average SAT scores are for the students in their area. They take a random sample of 100 students and find the average score is 1100 with a standard deviation of 200. What is a 95% confidence interval for the average SAT score of students in their area?


3. A garden center wants to store leftover packets of vegetable seeds for sale the following spring, but the center is concerned that the seeds may not germinate at the same rate a year later. The manager finds a packet of last year’s green bean seeds and plants them as a test. Although the packet claims a germination rate of 92%, only 171 of 200 test seeds sprout. Is this evidence that the seeds have lost viability during a year in storage? Test an appropriate hypothesis and state your conclusion. 

a) Write appropriate hypotheses.

b) What is a type I error in this context? Explain the ramifications of that error.

c) What is a type II error in this context? Explain the ramifications of that error.

d) Which is worse in this context?

e) Perform the test and find the p-value.

f) Make a graph

g) State your conclusion.



4. Data on a random sample of 100 births for babies in North Carolina can be found in ```../../data/births.csv```. Government officials are wondering if their messaging has convinced mothers to smoke less. The goal was to to get under 40% of pregnant women to smoke. Did they succeed?

a) Write appropriate hypotheses.

b) What is a type I error in this context? Explain the ramifications of that error.

c) What is a type II error in this context? Explain the ramifications of that error.

d) Which is worse in this context?

e) Perform the test and find the p-value.

f) Make a graph

g) State your conclusion.












